name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
